version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: Europe/Warsaw
  - package-ecosystem: gradle
    directory: "/app"
    schedule:
      interval: daily
      time: "00:00"
      timezone: Europe/Warsaw